### ISSUE TITLE
bad optic

### ISSUE THREAD

**Issue by Bestever2207** [Informatik2022Java/BJ-EUROPLE#2]
the ui is nor the yellow from the egg

**Comment by FeljxFeljx** [comment]
thanks for your feedback.
sadly I dont quite understand what you mean by "the yellow from the egg".
Do you refer to to the menu screen or to the actual game-screen when saying "bad optic"?
If you want to contribute, feel free to make a pull request or just let me know what specific aspect of the UI is 'bad'.

**Comment by Bestever2207** [comment]
everything. everything looks bad

**Comment by FeljxFeljx** [comment]
Beacause you don't give any usefull feedback, I will close this issue.
